version: '3.9'

services:
  appest:
    container_name: appest
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL = jdbc:postgresql://dbpa:5432/dbNorus
      - DATABASE_USERNAME = postgres
      - DATABASE_PASSWORD = postgres
    depends_on:
      - dbpa
  dbpa:
    container_name: dbpa
    image: postgres:15
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbNorus
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
